# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy/proxy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_cluster.common import common_type_pb2 as grpc__cluster_dot_common_dot_common__type__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proxy/proxy.proto',
  package='grpc_cluster.proxy',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11proxy/proxy.proto\x12\x12grpc_cluster.proxy\x1a%grpc_cluster/common/common_type.proto2\xe8\x0b\n\x05Proxy\x12k\n\x0euploadFileInfo\x12*.grpc_cluster.common.UploadFileInfoRequest\x1a+.grpc_cluster.common.UploadFileInfoResponse\"\x00\x12]\n\nuploadFile\x12&.grpc_cluster.common.UploadFileRequest\x1a#.grpc_cluster.common.StatusResponse\"\x00(\x01\x12g\n\x0c\x64ownloadFile\x12(.grpc_cluster.common.DownloadFileRequest\x1a).grpc_cluster.common.DownloadFileResponse\"\x00\x30\x01\x12g\n\x10getDirectoryList\x12,.grpc_cluster.common.GetDirectoryListRequest\x1a#.grpc_cluster.common.StatusResponse\"\x00\x12_\n\x0bgetFileInfo\x12\'.grpc_cluster.common.GetFileInfoRequest\x1a%.grpc_cluster.common.FileInfoResponse\"\x00\x12m\n\x13moveFileOrDirectory\x12/.grpc_cluster.common.MoveFileOrDirectoryRequest\x1a#.grpc_cluster.common.StatusResponse\"\x00\x12q\n\x15removeFileOrDirectory\x12\x31.grpc_cluster.common.RemoveFileOrDirectoryRequest\x1a#.grpc_cluster.common.StatusResponse\"\x00\x12\x63\n\x0e\x65xecuteCommand\x12*.grpc_cluster.common.ExecuteCommandRequest\x1a#.grpc_cluster.common.StatusResponse\"\x00\x12V\n\x08register\x12$.grpc_cluster.common.RegisterRequest\x1a\".grpc_cluster.common.TokenResponse\"\x00\x12R\n\x06signIn\x12\".grpc_cluster.common.SignInRequest\x1a\".grpc_cluster.common.TokenResponse\"\x00\x12k\n\x12\x63heckUserExistance\x12..grpc_cluster.common.CheckUserExistanceRequest\x1a#.grpc_cluster.common.StatusResponse\"\x00\x12]\n\x0bsendMessage\x12\'.grpc_cluster.common.SendMessageRequest\x1a#.grpc_cluster.common.StatusResponse\"\x00\x12V\n\x11getWelcomeMessage\x12\x1a.grpc_cluster.common.Token\x1a#.grpc_cluster.common.StatusResponse\"\x00\x12`\n\rlaunchWorkers\x12(.grpc_cluster.common.LaunchWorkerRequest\x1a#.grpc_cluster.common.StatusResponse\"\x00\x12g\n\x10\x63reateVirtualenv\x12,.grpc_cluster.common.CreateVirtualenvRequest\x1a#.grpc_cluster.common.StatusResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[grpc__cluster_dot_common_dot_common__type__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PROXY = _descriptor.ServiceDescriptor(
  name='Proxy',
  full_name='grpc_cluster.proxy.Proxy',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=81,
  serialized_end=1593,
  methods=[
  _descriptor.MethodDescriptor(
    name='uploadFileInfo',
    full_name='grpc_cluster.proxy.Proxy.uploadFileInfo',
    index=0,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._UPLOADFILEINFOREQUEST,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._UPLOADFILEINFORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='uploadFile',
    full_name='grpc_cluster.proxy.Proxy.uploadFile',
    index=1,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._UPLOADFILEREQUEST,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='downloadFile',
    full_name='grpc_cluster.proxy.Proxy.downloadFile',
    index=2,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._DOWNLOADFILEREQUEST,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._DOWNLOADFILERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getDirectoryList',
    full_name='grpc_cluster.proxy.Proxy.getDirectoryList',
    index=3,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._GETDIRECTORYLISTREQUEST,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getFileInfo',
    full_name='grpc_cluster.proxy.Proxy.getFileInfo',
    index=4,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._GETFILEINFOREQUEST,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._FILEINFORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='moveFileOrDirectory',
    full_name='grpc_cluster.proxy.Proxy.moveFileOrDirectory',
    index=5,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._MOVEFILEORDIRECTORYREQUEST,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='removeFileOrDirectory',
    full_name='grpc_cluster.proxy.Proxy.removeFileOrDirectory',
    index=6,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._REMOVEFILEORDIRECTORYREQUEST,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='executeCommand',
    full_name='grpc_cluster.proxy.Proxy.executeCommand',
    index=7,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._EXECUTECOMMANDREQUEST,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='register',
    full_name='grpc_cluster.proxy.Proxy.register',
    index=8,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._REGISTERREQUEST,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._TOKENRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='signIn',
    full_name='grpc_cluster.proxy.Proxy.signIn',
    index=9,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._SIGNINREQUEST,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._TOKENRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='checkUserExistance',
    full_name='grpc_cluster.proxy.Proxy.checkUserExistance',
    index=10,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._CHECKUSEREXISTANCEREQUEST,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sendMessage',
    full_name='grpc_cluster.proxy.Proxy.sendMessage',
    index=11,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._SENDMESSAGEREQUEST,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getWelcomeMessage',
    full_name='grpc_cluster.proxy.Proxy.getWelcomeMessage',
    index=12,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._TOKEN,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='launchWorkers',
    full_name='grpc_cluster.proxy.Proxy.launchWorkers',
    index=13,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._LAUNCHWORKERREQUEST,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='createVirtualenv',
    full_name='grpc_cluster.proxy.Proxy.createVirtualenv',
    index=14,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._CREATEVIRTUALENVREQUEST,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._STATUSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROXY)

DESCRIPTOR.services_by_name['Proxy'] = _PROXY

# @@protoc_insertion_point(module_scope)
