# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from grpc_cluster.common import common_type_pb2 as grpc__cluster_dot_common_dot_common__type__pb2


class ProxyStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.uploadFileInfo = channel.unary_unary(
        '/grpc_cluster.proxy.Proxy/uploadFileInfo',
        request_serializer=grpc__cluster_dot_common_dot_common__type__pb2.UploadFileInfoRequest.SerializeToString,
        response_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.UploadFileInfoResponse.FromString,
        )
    self.uploadFile = channel.stream_unary(
        '/grpc_cluster.proxy.Proxy/uploadFile',
        request_serializer=grpc__cluster_dot_common_dot_common__type__pb2.UploadFileRequest.SerializeToString,
        response_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.FromString,
        )
    self.downloadFile = channel.unary_stream(
        '/grpc_cluster.proxy.Proxy/downloadFile',
        request_serializer=grpc__cluster_dot_common_dot_common__type__pb2.DownloadFileRequest.SerializeToString,
        response_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.DownloadFileResponse.FromString,
        )
    self.getDirectoryList = channel.unary_unary(
        '/grpc_cluster.proxy.Proxy/getDirectoryList',
        request_serializer=grpc__cluster_dot_common_dot_common__type__pb2.GetDirectoryListRequest.SerializeToString,
        response_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.FromString,
        )
    self.getFileInfo = channel.unary_unary(
        '/grpc_cluster.proxy.Proxy/getFileInfo',
        request_serializer=grpc__cluster_dot_common_dot_common__type__pb2.GetFileInfoRequest.SerializeToString,
        response_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.FileInfoResponse.FromString,
        )
    self.moveFileOrDirectory = channel.unary_unary(
        '/grpc_cluster.proxy.Proxy/moveFileOrDirectory',
        request_serializer=grpc__cluster_dot_common_dot_common__type__pb2.MoveFileOrDirectoryRequest.SerializeToString,
        response_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.FromString,
        )
    self.removeFileOrDirectory = channel.unary_unary(
        '/grpc_cluster.proxy.Proxy/removeFileOrDirectory',
        request_serializer=grpc__cluster_dot_common_dot_common__type__pb2.RemoveFileOrDirectoryRequest.SerializeToString,
        response_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.FromString,
        )
    self.executeCommand = channel.unary_unary(
        '/grpc_cluster.proxy.Proxy/executeCommand',
        request_serializer=grpc__cluster_dot_common_dot_common__type__pb2.ExecuteCommandRequest.SerializeToString,
        response_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.FromString,
        )
    self.register = channel.unary_unary(
        '/grpc_cluster.proxy.Proxy/register',
        request_serializer=grpc__cluster_dot_common_dot_common__type__pb2.RegisterRequest.SerializeToString,
        response_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.TokenResponse.FromString,
        )
    self.signIn = channel.unary_unary(
        '/grpc_cluster.proxy.Proxy/signIn',
        request_serializer=grpc__cluster_dot_common_dot_common__type__pb2.SignInRequest.SerializeToString,
        response_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.TokenResponse.FromString,
        )
    self.checkUserExistance = channel.unary_unary(
        '/grpc_cluster.proxy.Proxy/checkUserExistance',
        request_serializer=grpc__cluster_dot_common_dot_common__type__pb2.CheckUserExistanceRequest.SerializeToString,
        response_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.FromString,
        )
    self.sendMessage = channel.unary_unary(
        '/grpc_cluster.proxy.Proxy/sendMessage',
        request_serializer=grpc__cluster_dot_common_dot_common__type__pb2.SendMessageRequest.SerializeToString,
        response_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.FromString,
        )
    self.getWelcomeMessage = channel.unary_unary(
        '/grpc_cluster.proxy.Proxy/getWelcomeMessage',
        request_serializer=grpc__cluster_dot_common_dot_common__type__pb2.Token.SerializeToString,
        response_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.FromString,
        )
    self.launchWorkers = channel.unary_unary(
        '/grpc_cluster.proxy.Proxy/launchWorkers',
        request_serializer=grpc__cluster_dot_common_dot_common__type__pb2.LaunchWorkerRequest.SerializeToString,
        response_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.FromString,
        )
    self.createVirtualenv = channel.unary_unary(
        '/grpc_cluster.proxy.Proxy/createVirtualenv',
        request_serializer=grpc__cluster_dot_common_dot_common__type__pb2.CreateVirtualenvRequest.SerializeToString,
        response_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.FromString,
        )


class ProxyServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def uploadFileInfo(self, request, context):
    """File
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def uploadFile(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def downloadFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getDirectoryList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getFileInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def moveFileOrDirectory(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def removeFileOrDirectory(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def executeCommand(self, request, context):
    """command line
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def register(self, request, context):
    """User
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def signIn(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def checkUserExistance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sendMessage(self, request, context):
    """Send Message
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getWelcomeMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def launchWorkers(self, request, context):
    """Application
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def createVirtualenv(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProxyServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'uploadFileInfo': grpc.unary_unary_rpc_method_handler(
          servicer.uploadFileInfo,
          request_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.UploadFileInfoRequest.FromString,
          response_serializer=grpc__cluster_dot_common_dot_common__type__pb2.UploadFileInfoResponse.SerializeToString,
      ),
      'uploadFile': grpc.stream_unary_rpc_method_handler(
          servicer.uploadFile,
          request_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.UploadFileRequest.FromString,
          response_serializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.SerializeToString,
      ),
      'downloadFile': grpc.unary_stream_rpc_method_handler(
          servicer.downloadFile,
          request_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.DownloadFileRequest.FromString,
          response_serializer=grpc__cluster_dot_common_dot_common__type__pb2.DownloadFileResponse.SerializeToString,
      ),
      'getDirectoryList': grpc.unary_unary_rpc_method_handler(
          servicer.getDirectoryList,
          request_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.GetDirectoryListRequest.FromString,
          response_serializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.SerializeToString,
      ),
      'getFileInfo': grpc.unary_unary_rpc_method_handler(
          servicer.getFileInfo,
          request_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.GetFileInfoRequest.FromString,
          response_serializer=grpc__cluster_dot_common_dot_common__type__pb2.FileInfoResponse.SerializeToString,
      ),
      'moveFileOrDirectory': grpc.unary_unary_rpc_method_handler(
          servicer.moveFileOrDirectory,
          request_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.MoveFileOrDirectoryRequest.FromString,
          response_serializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.SerializeToString,
      ),
      'removeFileOrDirectory': grpc.unary_unary_rpc_method_handler(
          servicer.removeFileOrDirectory,
          request_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.RemoveFileOrDirectoryRequest.FromString,
          response_serializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.SerializeToString,
      ),
      'executeCommand': grpc.unary_unary_rpc_method_handler(
          servicer.executeCommand,
          request_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.ExecuteCommandRequest.FromString,
          response_serializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.SerializeToString,
      ),
      'register': grpc.unary_unary_rpc_method_handler(
          servicer.register,
          request_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.RegisterRequest.FromString,
          response_serializer=grpc__cluster_dot_common_dot_common__type__pb2.TokenResponse.SerializeToString,
      ),
      'signIn': grpc.unary_unary_rpc_method_handler(
          servicer.signIn,
          request_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.SignInRequest.FromString,
          response_serializer=grpc__cluster_dot_common_dot_common__type__pb2.TokenResponse.SerializeToString,
      ),
      'checkUserExistance': grpc.unary_unary_rpc_method_handler(
          servicer.checkUserExistance,
          request_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.CheckUserExistanceRequest.FromString,
          response_serializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.SerializeToString,
      ),
      'sendMessage': grpc.unary_unary_rpc_method_handler(
          servicer.sendMessage,
          request_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.SendMessageRequest.FromString,
          response_serializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.SerializeToString,
      ),
      'getWelcomeMessage': grpc.unary_unary_rpc_method_handler(
          servicer.getWelcomeMessage,
          request_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.Token.FromString,
          response_serializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.SerializeToString,
      ),
      'launchWorkers': grpc.unary_unary_rpc_method_handler(
          servicer.launchWorkers,
          request_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.LaunchWorkerRequest.FromString,
          response_serializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.SerializeToString,
      ),
      'createVirtualenv': grpc.unary_unary_rpc_method_handler(
          servicer.createVirtualenv,
          request_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.CreateVirtualenvRequest.FromString,
          response_serializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc_cluster.proxy.Proxy', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
