master:
    name: "master00"
    addr: "localhost:9999"

proxy:
    - name: "proxy01"
      addr: "localhost:50040"
      default_entrypoint: "run.py"
      default_venv: "atari"
      workers:
          - name: "slave"
            port: 6660-6661
venv:
    - name: "atari"
      params:
          - python=python3.6
      requirements:
          - grpcio
          - gym
          - gym_super_mario_bros
          - --no-binary=protobuf protobuf
          - dill
