# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from grpc_cluster.common import common_type_pb2 as grpc__cluster_dot_common_dot_common__type__pb2
from grpc_cluster.worker import worker_type_pb2 as grpc__cluster_dot_worker_dot_worker__type__pb2


class WorkerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sendData = channel.unary_unary(
        '/grpc_cluster.worker.Worker/sendData',
        request_serializer=grpc__cluster_dot_common_dot_common__type__pb2.SendDataRequest.SerializeToString,
        response_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.FromString,
        )
    self.sendMessage = channel.unary_unary(
        '/grpc_cluster.worker.Worker/sendMessage',
        request_serializer=grpc__cluster_dot_common_dot_common__type__pb2.SendMessageRequest.SerializeToString,
        response_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.FromString,
        )
    self.getMessages = channel.unary_unary(
        '/grpc_cluster.worker.Worker/getMessages',
        request_serializer=grpc__cluster_dot_worker_dot_worker__type__pb2.GetMessagesRequest.SerializeToString,
        response_deserializer=grpc__cluster_dot_worker_dot_worker__type__pb2.GetMessagesResponse.FromString,
        )
    self.shutdown = channel.unary_unary(
        '/grpc_cluster.worker.Worker/shutdown',
        request_serializer=grpc__cluster_dot_worker_dot_worker__type__pb2.ShutdownRequest.SerializeToString,
        response_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.FromString,
        )
    self.getWelcomeMessage = channel.unary_unary(
        '/grpc_cluster.worker.Worker/getWelcomeMessage',
        request_serializer=grpc__cluster_dot_common_dot_common__type__pb2.Token.SerializeToString,
        response_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.FromString,
        )


class WorkerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def sendData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sendMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getMessages(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def shutdown(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getWelcomeMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WorkerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sendData': grpc.unary_unary_rpc_method_handler(
          servicer.sendData,
          request_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.SendDataRequest.FromString,
          response_serializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.SerializeToString,
      ),
      'sendMessage': grpc.unary_unary_rpc_method_handler(
          servicer.sendMessage,
          request_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.SendMessageRequest.FromString,
          response_serializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.SerializeToString,
      ),
      'getMessages': grpc.unary_unary_rpc_method_handler(
          servicer.getMessages,
          request_deserializer=grpc__cluster_dot_worker_dot_worker__type__pb2.GetMessagesRequest.FromString,
          response_serializer=grpc__cluster_dot_worker_dot_worker__type__pb2.GetMessagesResponse.SerializeToString,
      ),
      'shutdown': grpc.unary_unary_rpc_method_handler(
          servicer.shutdown,
          request_deserializer=grpc__cluster_dot_worker_dot_worker__type__pb2.ShutdownRequest.FromString,
          response_serializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.SerializeToString,
      ),
      'getWelcomeMessage': grpc.unary_unary_rpc_method_handler(
          servicer.getWelcomeMessage,
          request_deserializer=grpc__cluster_dot_common_dot_common__type__pb2.Token.FromString,
          response_serializer=grpc__cluster_dot_common_dot_common__type__pb2.StatusResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc_cluster.worker.Worker', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
