# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker/worker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_cluster.common import common_type_pb2 as grpc__cluster_dot_common_dot_common__type__pb2
from grpc_cluster.worker import worker_type_pb2 as grpc__cluster_dot_worker_dot_worker__type__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='worker/worker.proto',
  package='grpc_cluster.worker',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13worker/worker.proto\x12\x13grpc_cluster.worker\x1a%grpc_cluster/common/common_type.proto\x1a%grpc_cluster/worker/worker_type.proto2\xd5\x03\n\x06Worker\x12W\n\x08sendData\x12$.grpc_cluster.common.SendDataRequest\x1a#.grpc_cluster.common.StatusResponse\"\x00\x12]\n\x0bsendMessage\x12\'.grpc_cluster.common.SendMessageRequest\x1a#.grpc_cluster.common.StatusResponse\"\x00\x12\x62\n\x0bgetMessages\x12\'.grpc_cluster.worker.GetMessagesRequest\x1a(.grpc_cluster.worker.GetMessagesResponse\"\x00\x12W\n\x08shutdown\x12$.grpc_cluster.worker.ShutdownRequest\x1a#.grpc_cluster.common.StatusResponse\"\x00\x12V\n\x11getWelcomeMessage\x12\x1a.grpc_cluster.common.Token\x1a#.grpc_cluster.common.StatusResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[grpc__cluster_dot_common_dot_common__type__pb2.DESCRIPTOR,grpc__cluster_dot_worker_dot_worker__type__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_WORKER = _descriptor.ServiceDescriptor(
  name='Worker',
  full_name='grpc_cluster.worker.Worker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=123,
  serialized_end=592,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendData',
    full_name='grpc_cluster.worker.Worker.sendData',
    index=0,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._SENDDATAREQUEST,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sendMessage',
    full_name='grpc_cluster.worker.Worker.sendMessage',
    index=1,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._SENDMESSAGEREQUEST,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getMessages',
    full_name='grpc_cluster.worker.Worker.getMessages',
    index=2,
    containing_service=None,
    input_type=grpc__cluster_dot_worker_dot_worker__type__pb2._GETMESSAGESREQUEST,
    output_type=grpc__cluster_dot_worker_dot_worker__type__pb2._GETMESSAGESRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='shutdown',
    full_name='grpc_cluster.worker.Worker.shutdown',
    index=3,
    containing_service=None,
    input_type=grpc__cluster_dot_worker_dot_worker__type__pb2._SHUTDOWNREQUEST,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getWelcomeMessage',
    full_name='grpc_cluster.worker.Worker.getWelcomeMessage',
    index=4,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._TOKEN,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._STATUSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKER)

DESCRIPTOR.services_by_name['Worker'] = _WORKER

# @@protoc_insertion_point(module_scope)
