# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth/jwt_auth.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_cluster.service.rpc.auth import jwt_auth_type_pb2 as grpc__cluster_dot_service_dot_rpc_dot_auth_dot_jwt__auth__type__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='auth/jwt_auth.proto',
  package='grpc_cluster.service.rpc.auth',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x61uth/jwt_auth.proto\x12\x1dgrpc_cluster.service.rpc.auth\x1a\x31grpc_cluster/service/rpc/auth/jwt_auth_type.proto2v\n\x0e\x41uthentication\x12\x64\n\x05Login\x12+.grpc_cluster.service.rpc.auth.LoginRequest\x1a,.grpc_cluster.service.rpc.auth.LoginResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[grpc__cluster_dot_service_dot_rpc_dot_auth_dot_jwt__auth__type__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_AUTHENTICATION = _descriptor.ServiceDescriptor(
  name='Authentication',
  full_name='grpc_cluster.service.rpc.auth.Authentication',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=105,
  serialized_end=223,
  methods=[
  _descriptor.MethodDescriptor(
    name='Login',
    full_name='grpc_cluster.service.rpc.auth.Authentication.Login',
    index=0,
    containing_service=None,
    input_type=grpc__cluster_dot_service_dot_rpc_dot_auth_dot_jwt__auth__type__pb2._LOGINREQUEST,
    output_type=grpc__cluster_dot_service_dot_rpc_dot_auth_dot_jwt__auth__type__pb2._LOGINRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTHENTICATION)

DESCRIPTOR.services_by_name['Authentication'] = _AUTHENTICATION

# @@protoc_insertion_point(module_scope)
