# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from grpc_cluster.service.rpc.auth.jwt import auth_type_pb2 as grpc__cluster_dot_service_dot_rpc_dot_auth_dot_jwt_dot_auth__type__pb2


class AuthenticationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Login = channel.unary_unary(
        '/grpc_cluster.auth.jwt.Authentication/Login',
        request_serializer=grpc__cluster_dot_service_dot_rpc_dot_auth_dot_jwt_dot_auth__type__pb2.LoginRequest.SerializeToString,
        response_deserializer=grpc__cluster_dot_service_dot_rpc_dot_auth_dot_jwt_dot_auth__type__pb2.LoginResponse.FromString,
        )


class AuthenticationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AuthenticationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Login': grpc.unary_unary_rpc_method_handler(
          servicer.Login,
          request_deserializer=grpc__cluster_dot_service_dot_rpc_dot_auth_dot_jwt_dot_auth__type__pb2.LoginRequest.FromString,
          response_serializer=grpc__cluster_dot_service_dot_rpc_dot_auth_dot_jwt_dot_auth__type__pb2.LoginResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpc_cluster.auth.jwt.Authentication', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
