# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master/master.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from grpc_cluster.common import common_type_pb2 as grpc__cluster_dot_common_dot_common__type__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='master/master.proto',
  package='grpc_cluster.master',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13master/master.proto\x12\x13grpc_cluster.master\x1a%grpc_cluster/common/common_type.proto2\x98\x02\n\x06Master\x12W\n\x08sendData\x12$.grpc_cluster.common.SendDataRequest\x1a#.grpc_cluster.common.StatusResponse\"\x00\x12]\n\x0bsendMessage\x12\'.grpc_cluster.common.SendMessageRequest\x1a#.grpc_cluster.common.StatusResponse\"\x00\x12V\n\x11getWelcomeMessage\x12\x1a.grpc_cluster.common.Token\x1a#.grpc_cluster.common.StatusResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[grpc__cluster_dot_common_dot_common__type__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MASTER = _descriptor.ServiceDescriptor(
  name='Master',
  full_name='grpc_cluster.master.Master',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=84,
  serialized_end=364,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendData',
    full_name='grpc_cluster.master.Master.sendData',
    index=0,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._SENDDATAREQUEST,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sendMessage',
    full_name='grpc_cluster.master.Master.sendMessage',
    index=1,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._SENDMESSAGEREQUEST,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._STATUSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getWelcomeMessage',
    full_name='grpc_cluster.master.Master.getWelcomeMessage',
    index=2,
    containing_service=None,
    input_type=grpc__cluster_dot_common_dot_common__type__pb2._TOKEN,
    output_type=grpc__cluster_dot_common_dot_common__type__pb2._STATUSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTER)

DESCRIPTOR.services_by_name['Master'] = _MASTER

# @@protoc_insertion_point(module_scope)
